### ISSUE TITLE
Development environment?

### ISSUE THREAD

**Issue by fritzophrenic** [fireout/keepasssequencer#23]
I think we should document the development environment somewhere in the wiki.

I bring this up because I'm trying to set up to work on the project on a different computer than I had been using, and the Visual Studio version I had been using (2010 express) is not available for download anymore, as far as I can tell. I'm not sure which version to install at this point.

So what are you using to develop, currently? I don't want to commit anything that interferes with your setup, if I can avoid it.

**Comment by fireout** [comment]
It's not a bad idea, although I think what is important to highlight is what changes (in the csproj and the sln file) is relevant to the development environment, just so they are not pushed with actual feature changes.  Plus, I'm not sure myself about all the specific that may be relevant, do you have a sample document that I could base myself on?

For now, if you have changes that you are not sure about, I can checkout your branch and see if it works fine with my setup...

I'm currently using VS2013, but since 2010 SP1, changes to the project/solution files are backward compatible, as long as we stay on the same .NET Framework.

**Comment by fireout** [comment]
Just as a FYI, I tried running with VS 2015 Community, works good.

I'll update the doc
