### ISSUE TITLE
Missing visual studio project

### ISSUE THREAD

**Issue by fritzophrenic** [fireout/keepasssequencer#26]
There is an error every time I open the Visual Studio solution, "One or more projects in the solution were not loaded correctly."

It's because the SequenceTester project does not exist in the repository. Please either add this or remove it from the solution.

**Comment by fireout** [comment]
I did remember you told me this a while ago, I did remove it from the solution file just today.
I also pushed (in the ui-discussion branch) a sample Sequencer.csproj.user.

If you debug with Visual studio, you can change the bin\debug\keepass.exe to the absolute path of where your bin folder is, and starting to debug will automatically start keepass.

I'll merge ui-discussion in develop when you confirm the issue is resolved.

**Comment by fritzophrenic** [comment]
Yes, the solution loads without errors now, and I can start up a debugger just fine without changing anything.

**Comment by fritzophrenic** [comment]
Fixed by db0f83e180a80153fdd6ae5807aff0be298dc9a4
