### ISSUE TITLE
Support Diceware (and maybe "multiple" algorythm)

### ISSUE THREAD

**Issue by fireout** [fireout/keepasssequencer#3]
Diceware algorythm (http://world.std.com/~reinhold/diceware.html) generated stronger password.  This algorythm should be used when generating sequence, along with, eventually, other algorythm.

wordsequencer should allow for algorytghm selection.

**Comment by fritzophrenic** [comment]
I think the best way to do this is to implement #5 and #6 so that we can ship the plugin with a few pre-made configurations. Really the different algorithms are just different word lists (and maybe capitalization strategies).

Is this basically what you had in mind or did you have a different idea?

I want to suggest these lists for distribution:
- The [main Diceware list](http://world.std.com/~reinhold/diceware.wordlist.asc) -- Creative Commons license
- The [alternate Beale Diceware list](http://world.std.com/~reinhold/beale.wordlist.asc) -- Creative Commons license
- The [New General Service List](http://www.newgeneralservicelist.org/) (NGSL) -- Creative Commons license
- The [most frequently used 5000 English words](http://www.wordfrequency.info/free.asp) -- not an "open" copyright but we have permission to use it as long as we link back to the webpage (I asked the author specifically).

Those last two would need spaces or punctuation or something between words to ensure we don't accidentally weaken the passwords by combining words into other words in the list.

**Comment by fireout** [comment]
Yes and no, I'm all for publishing sample word lists but the diceware algorythm also implies selecting words using a different method, at least that's what I understood?

**Comment by fritzophrenic** [comment]
Diceware just makes it easy to come up with random words "by hand". It has exactly 6^5 words in its word list, and it provides a numeric index for each word where each index is 5 digits using only digits 1-6. This lets you roll 5 dice to get an index.

The only reason I know of to use this scheme to pick a word, is so that the average user can generate a high-quality random number using dice they probably already have in their home. Generating a number between 1 and 6^5, and selecting that word from the word list, will achieve the same thing. You just can't really get such a number very easily using dice. However, since we're using a high-quality PRNG in a computer-based password generator, we can use our normal method rather than trying to simulate dice rolls.

**Comment by fireout** [comment]
Issue resolved with merged pr
